# Provides definitions for all vehicles to be used in the scenario
title:            "Training ego vehicle"
vehicles:

  - id:           0 ########################## always the ego vehicle
    model:        BridgitModel
    guidance:     BridgitGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    3.0     #m/s^2
    length:       5.0     #m
    lc_duration:  3.2     #sec #needs to be an even multiple of time step 0.2 sec

  - id:           1 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           2 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           3 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           4 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           5 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           6 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           7 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           8 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           9 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           10 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           11 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           12 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           13 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           14 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           15 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec

  - id:           16 ##########################
    model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec
