# Provides definitions for all vehicles to be used in the scenario
title:            "Training ego vehicle"

ego:
  model:        BridgitModel
  guidance:     BridgitGuidance
  max_jerk:     4.0     #m/s^3
  max_accel:    3.0     #m/s^2
  length:       5.0     #m
  lc_duration:  3.2     #sec #needs to be an even multiple of time step 0.2 sec

#---------- NEIGHBOR VEHICLES

# The specified vehicle counts of each type will be created in the master list of neighbor vehicles.
# The sum of their counts is the total number of vehicles available for use. Some subset of this master
# list will be selected for any given episode.
# count = 0 is a valid selection.
vehicle_types:

  - model:        BridgitModel
    guidance:     BridgitGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    3.0     #m/s^2
    length:       5.0     #m
    lc_duration:  3.2     #sec
    count:        4

  - model:        BotType1Model
    guidance:     BotType1aGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    3.0     #m/s^2
    length:       12.0     #m
    lc_duration:  2.4     #sec
    count:        2

  - model:        BotType1Model
    guidance:     BotType1bGuidance
    max_jerk:     4.0     #m/s^3
    max_accel:    4.0     #m/s^2
    length:       5.0     #m
    lc_duration:  2.4     #sec
    count:        10
